package view;

import controller.userCreate;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.registro;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author samir
 */
public class accountRecovery extends javax.swing.JPanel {

    private main main;
    private userCreate dt;
    registro mensajero = new registro();

    public accountRecovery(main main, userCreate dt) {
        this.main = main;
        this.dt = dt;
        initComponents();
        campos();
    }

    private void campos() {
        lbUser.setText(dt.getUser() + " ingresa una nueva contraseña para acceder a tu cuenta.");
    }

    private void reestablecerPass() {
        try {
            String newPass = txtPass1.getText();
            String confirmPass = txtConfirmPass.getText();
            boolean confirm = true;

            if (newPass.equals("") && confirmPass.equals("")) {
                JOptionPane.showMessageDialog(null, "¡Llena todos los campos!", "Llena los campos", JOptionPane.INFORMATION_MESSAGE);
                confirm = false;
            }
            if (confirm == true) {
                if (newPass.equals(confirmPass)) {
                    String newPasword = DigestUtils.sha1Hex(newPass);
                    boolean set = mensajero.reestablecerPass(dt, newPasword);
                    if (set == true) {
                        main.irlogin(this, dt);
                    } else {
                        JOptionPane.showMessageDialog(null, "¡Vuelve a intentar!", "Verificando...!", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "¡Bro esas contraseñas no coinciden!", "Verificando...!", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "¡Error, estamos trabajando en ello!", "Recuperar contraseña", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTransparente1 = new LIB.JPanelTransparente();
        jLabel1 = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();
        txtPass1 = new javax.swing.JPasswordField();
        kButton1 = new keeptoo.KButton();

        setBackground(new java.awt.Color(27, 40, 56));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTransparente1.setBackground(new java.awt.Color(27, 40, 56));
        jPanelTransparente1.setColorPrimario(new java.awt.Color(27, 40, 56));
        jPanelTransparente1.setColorSecundario(new java.awt.Color(27, 40, 56));
        jPanelTransparente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restablecer");
        jPanelTransparente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 260, -1));

        lbUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbUser.setForeground(new java.awt.Color(102, 102, 102));
        jPanelTransparente1.add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 70, 260, 20));

        txtConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPassActionPerformed(evt);
            }
        });
        jPanelTransparente1.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, 30));
        jPanelTransparente1.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 30));

        kButton1.setText("Reset Password");
        kButton1.setBorderPainted(false);
        kButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton1.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton1.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanelTransparente1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        add(jPanelTransparente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, 309));
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPassActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        reestablecerPass();
    }//GEN-LAST:event_kButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private LIB.JPanelTransparente jPanelTransparente1;
    private keeptoo.KButton kButton1;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JPasswordField txtPass1;
    // End of variables declaration//GEN-END:variables
}
