package view;

import controller.userCreate;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.registro;

/**
 *
 * @author Karen Espitia
 */
public class Inventario extends javax.swing.JPanel {

    private main main;
    private userCreate dt;
    registro rg = new registro();

    public Inventario(main main, userCreate dt) {
        this.main = main;
        this.dt = dt;
        initComponents();
        btn_ver.setVisible(false);
        //indice.setVisible(false);
        jLabel7.setVisible(false);
        kButton1.setVisible(false);
        txtimagen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRound1 = new LIB.JPanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtimagen = new javax.swing.JTextField();
        tipoc = new javax.swing.JComboBox<>();
        txtmarca = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        txtnomotor = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        imagen = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_ver = new keeptoo.KButton();
        indice = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        btnNuevo = new keeptoo.KButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 40, 56));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound1.setColorPrimario(new java.awt.Color(27, 40, 56));
        jPanelRound1.setColorSecundario(new java.awt.Color(27, 40, 56));
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Color");
        jPanelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa");
        jPanelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo");
        jPanelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NoMotor");
        jPanelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ciudad");
        jPanelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Marca");
        jPanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de carro");
        jPanelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Imagen");
        jPanelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 20));

        txtimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimagenActionPerformed(evt);
            }
        });
        jPanelRound1.add(txtimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 150, 20));

        tipoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "deportivo", "clasico", "todoterreno", "pickup", "city car" }));
        jPanelRound1.add(tipoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, 30));

        txtmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarcaActionPerformed(evt);
            }
        });
        jPanelRound1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, 20));
        jPanelRound1.add(txtciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, 20));
        jPanelRound1.add(txtnomotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, 20));
        jPanelRound1.add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, 20));
        jPanelRound1.add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, 20));
        jPanelRound1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, 20));

        imagen.setForeground(new java.awt.Color(0, 0, 0));
        jPanelRound1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 160, 170));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Registrar inventario");
        jPanelRound1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btn_ver.setText("Ver");
        btn_ver.setBorderPainted(false);
        btn_ver.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_ver.setkAllowGradient(false);
        btn_ver.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        btn_ver.setkEndColor(new java.awt.Color(102, 102, 255));
        btn_ver.setkHoverColor(new java.awt.Color(153, 255, 153));
        btn_ver.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        btn_ver.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_ver.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        btn_ver.setkSelectedColor(new java.awt.Color(255, 0, 0));
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });
        jPanelRound1.add(btn_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 30, 20));

        indice.setBackground(new java.awt.Color(51, 0, 102));
        indice.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        indice.setText("2");
        jPanelRound1.add(indice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 10, -1));

        kButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_upload_to_cloud_16px_1.png"))); // NOI18N
        kButton1.setText("Seleccionar");
        kButton1.setBorderPainted(false);
        kButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton1.setIconTextGap(8);
        kButton1.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton1.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        kButton1.setkSelectedColor(new java.awt.Color(255, 102, 153));
        kButton1.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanelRound1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 140, -1));

        kButton2.setText("Aceptar");
        kButton2.setBorderPainted(false);
        kButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton2.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        kButton2.setkSelectedColor(new java.awt.Color(255, 102, 153));
        kButton2.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanelRound1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 100, 40));

        btnNuevo.setText("Nuevo");
        btnNuevo.setBorderPainted(false);
        btnNuevo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnNuevo.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        btnNuevo.setkEndColor(new java.awt.Color(102, 102, 255));
        btnNuevo.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        btnNuevo.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNuevo.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        btnNuevo.setkSelectedColor(new java.awt.Color(255, 102, 153));
        btnNuevo.setkStartColor(new java.awt.Color(22, 32, 45));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanelRound1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 100, 40));

        add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 470, 440));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/izquierda_1.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addCar.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void txtimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimagenActionPerformed

    private void txtmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmarcaActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        main.irmenu(this, dt);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        main.irmostrarInventario(this, dt);
    }//GEN-LAST:event_btn_verActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        //CLase JFileChooser
        //Filtro para buscar imagen
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG; *.JPEG)", "jpg", "jpeg");

        JFileChooser img = new JFileChooser();
        img.addChoosableFileFilter(filtro);
        img.setDialogTitle("Abrir Archivo");
        //Declaro para que se abra la ventana del buscador
        int ventana = img.showOpenDialog(null);
        //Condicional para ver si se seleccionó un archivo
        if (ventana == JFileChooser.APPROVE_OPTION) {
            File fl = img.getSelectedFile();
            //Mostrar la ruta del archivo
            txtimagen.setText(String.valueOf(fl));
            //Imprimir imagen  seleccionada en el label
            Image imag = getToolkit().getImage(txtimagen.getText());
            imag = imag.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            imagen.setIcon(new ImageIcon(imag));

        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        agregarinv();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void agregarinv() {

        //FileInputStream archivarfoto = null;
        String placa = txtplaca.getText();
        String modelo = txtmodelo.getText();
        String NoMotor = txtnomotor.getText();
        String ciudad = txtciudad.getText();
        String Marca = txtmarca.getText();
        String tipoca = tipoc.getSelectedItem().toString();
        String color = txtColor.getText();
        String in = indice.getText();
//        try {
//            archivarfoto = new FileInputStream(txtimagen.getText());
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
//        }
        if (placa.equals("") || modelo.equals("") || NoMotor.equals("") || ciudad.equals("") || Marca.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor llena todos los campos!");
        }
        //rg.registrarInventario(placa, modelo, NoMotor, NoMotor, ciudad, Marca, tipoca, archivarfoto);
        //boolean registro = rg.registrarInventario(placa, modelo, color, NoMotor, ciudad, Marca, tipoca, archivarfoto);
        boolean registro = rg.registrarInventario(placa, modelo, color, NoMotor, ciudad, Marca, tipoca, in);
        if (registro != false) {
            JOptionPane.showMessageDialog(null, "Registro Exitoso!!");
            //btn_ver.setVisible(true);
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Error al crear el inventario, estamos trabajando el ello...!");
            btn_ver.setVisible(false);
        }
    }

    private void limpiar() {
        txtplaca.setText(null);
        txtmodelo.setText(null);
        txtnomotor.setText(null);
        txtciudad.setText(null);
        txtmarca.setText(null);
        txtimagen.setText(null);

        txtplaca.setEnabled(false);
        txtmodelo.setEnabled(false);
        txtnomotor.setEnabled(false);
        txtciudad.setEnabled(false);
        txtmarca.setEnabled(false);
        txtimagen.setEnabled(false);
    }

    private void nuevo() {
        txtplaca.setEnabled(true);
        txtmodelo.setEnabled(true);
        txtnomotor.setEnabled(true);
        txtciudad.setEnabled(true);
        txtmarca.setEnabled(true);
        txtimagen.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnNuevo;
    private keeptoo.KButton btn_ver;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel indice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private LIB.JPanelRound jPanelRound1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private javax.swing.JComboBox<String> tipoc;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtimagen;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnomotor;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
