package view;

import controller.Listas;
import controller.userCreate;
import java.awt.HeadlessException;
import static java.util.Objects.hash;
import javax.swing.JOptionPane;
import model.Hash;
import model.registro;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author yonier
 */
public class login extends javax.swing.JPanel {

    private main main;
    private userCreate dt;
    registro mensajero = new registro();

    public login(main main, userCreate dt) {
        this.main = main;
        this.dt = dt;
        initComponents();
    }

    private void login(String user, String pwd) {
        //String passCifrado = Hash.md5(pwd);
        if (txtUser.equals("") || txtPass.equals("")) {
            JOptionPane.showMessageDialog(null, "¡Llena todos los campos!");
        } else {
            userCreate data = mensajero.loginn(user, pwd);

            Listas<userCreate> dato = mensajero.consultarUsuarioss(user);
            if (data != null) {
                if (data.getRol() == 1) {
                    if (dato != null) {
                        //JOptionPane.showMessageDialog(null, "¡Te damos la bienvenida!" + data.getUser(), "Login incorrecto", JOptionPane.INFORMATION_MESSAGE);
                        main.irSplashCreen(this, dt);
                    }
                } else if (data.getRol() == 2) {
                    if (dato != null) {
                        main.irSplashCreen2(this, dt);
                    } else {
                        JOptionPane.showMessageDialog(null, "¡Por favor registrate y prueba de nuevo!", "Login incorrecto", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "¡Usuario o contraseña incorrectos!", "Login incorrecto", JOptionPane.ERROR_MESSAGE);
            }
        }
        //private  String usuario = txtUser.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUser = new LIB.FSTexFieldMD();
        jSeparator2 = new javax.swing.JSeparator();
        txtPass = new LIB.FSPasswordFieldMD();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_ingresar = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¡Ingresa ya!, encuentra los mejores automoviles ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("y productos para tu carro!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 720));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/usuario.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setForeground(new java.awt.Color(23, 146, 244));
        txtUser.setBordeColorFocus(new java.awt.Color(23, 146, 244));
        txtUser.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtUser.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtUser.setMaterialDesing(true);
        txtUser.setPlaceholder("Usuario");
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 390, 70));

        jSeparator2.setBackground(new java.awt.Color(153, 0, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 390, 20));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setForeground(new java.awt.Color(23, 146, 244));
        txtPass.setBordeColorFocus(new java.awt.Color(23, 146, 244));
        txtPass.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtPass.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtPass.setMaterialDesing(true);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 390, 70));

        jSeparator1.setBackground(new java.awt.Color(153, 0, 204));
        jSeparator1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator1MouseClicked(evt);
            }
        });
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 390, 20));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(23, 146, 244));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¿Olvidaste tu contraseña?");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 160, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/password.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 30, 30));

        btn_ingresar.setBackground(new java.awt.Color(51, 75, 166));
        btn_ingresar.setBorder(null);
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setBorderPainted(false);
        btn_ingresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_ingresar.setkBackGroundColor(new java.awt.Color(255, 153, 153));
        btn_ingresar.setkEndColor(new java.awt.Color(255, 153, 153));
        btn_ingresar.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        btn_ingresar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_ingresar.setkHoverStartColor(new java.awt.Color(255, 0, 102));
        btn_ingresar.setkStartColor(new java.awt.Color(51, 75, 166));
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, 260, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo interfaz (5).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 210, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo interfaz (4).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo interfaz (3).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 230, 190));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        String usuario = txtUser.getText();
        String pas = txtPass.getText();
        login(usuario, pas);
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void jSeparator1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator1MouseClicked
        main.irResetPass(this, dt);
    }//GEN-LAST:event_jSeparator1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_ingresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private LIB.FSPasswordFieldMD txtPass;
    private LIB.FSTexFieldMD txtUser;
    // End of variables declaration//GEN-END:variables
}
