package view;

import controller.Cola;
import controller.Listas;
import controller.Pila;
import controller.inventarioCarrosCr;
import controller.productoscreate;
import controller.userCreate;
import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.registro;

/**
 *
 * @author yonier
 */
public class menuUsuarios extends javax.swing.JPanel {

    private main main;
    private userCreate dt;
    private productoscreate pc;
    private inventarioCarrosCr ic;

    registro mensajero = new registro();

    public menuUsuarios(main main, userCreate dt) {
        this.main = main;
        this.dt = dt;
        initComponents();
    }

    void setColor(JPanel panel) { //51,51,55
        panel.setBackground(new Color(86, 70, 117));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(65, 48, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlUsers = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rSLabelHora2 = new rojeru_san.RSLabelHora();
        rSLabelFecha2 = new rojeru_san.RSLabelFecha();
        kButton6 = new keeptoo.KButton();
        kButton5 = new keeptoo.KButton();
        jLabel6 = new javax.swing.JLabel();
        pnlInventario = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        rSLabelHora5 = new rojeru_san.RSLabelHora();
        rSLabelFecha5 = new rojeru_san.RSLabelFecha();
        kButton7 = new keeptoo.KButton();
        kButton8 = new keeptoo.KButton();
        jLabel15 = new javax.swing.JLabel();
        pnlProductos = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        rSLabelHora4 = new rojeru_san.RSLabelHora();
        rSLabelFecha4 = new rojeru_san.RSLabelFecha();
        kButton9 = new keeptoo.KButton();
        kButton10 = new keeptoo.KButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kButton3 = new keeptoo.KButton();
        kButton4 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblUser1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(820, 720));
        jPanel2.setLayout(new java.awt.CardLayout());

        pnlUsers.setBackground(new java.awt.Color(18, 30, 49));
        pnlUsers.setMaximumSize(new java.awt.Dimension(820, 720));
        pnlUsers.setMinimumSize(new java.awt.Dimension(820, 720));
        pnlUsers.setPreferredSize(new java.awt.Dimension(980, 720));
        pnlUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(153, 153, 153));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Gestionar usuario");
        pnlUsers.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 500, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sinFD.png"))); // NOI18N
        pnlUsers.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 40, 56));
        jLabel5.setText("Burnz Buttly");
        pnlUsers.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        jPanel5.setBackground(new java.awt.Color(18, 30, 49));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelHora2.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelHora2.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        jPanel5.add(rSLabelHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 290, 70));

        rSLabelFecha2.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelFecha2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        jPanel5.add(rSLabelFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, -1));

        pnlUsers.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 380, 210));

        kButton6.setText("Registrar Usuarios");
        kButton6.setBorderPainted(false);
        kButton6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton6.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton6.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton6.setkPressedColor(new java.awt.Color(255, 0, 102));
        kButton6.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        pnlUsers.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, 80));

        kButton5.setText("Mostrar & Buscar");
        kButton5.setBorderPainted(false);
        kButton5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton5.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton5.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton5.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        pnlUsers.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 160, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marginalia-car-rental(1)_1.png"))); // NOI18N
        pnlUsers.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 250, 230));

        jPanel2.add(pnlUsers, "card3");

        pnlInventario.setBackground(new java.awt.Color(18, 30, 49));
        pnlInventario.setMaximumSize(new java.awt.Dimension(820, 720));
        pnlInventario.setMinimumSize(new java.awt.Dimension(820, 720));
        pnlInventario.setPreferredSize(new java.awt.Dimension(980, 720));
        pnlInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(153, 153, 153));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Gestionar inventario");
        pnlInventario.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 500, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sinFD.png"))); // NOI18N
        pnlInventario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(27, 40, 56));
        jLabel14.setText("Burnz Buttly");
        pnlInventario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        jPanel9.setBackground(new java.awt.Color(18, 30, 49));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelHora5.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelHora5.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        jPanel9.add(rSLabelHora5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 290, 70));

        rSLabelFecha5.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelFecha5.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        jPanel9.add(rSLabelFecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, -1));

        pnlInventario.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 380, 210));

        kButton7.setText("Registrar Inventario");
        kButton7.setBorderPainted(false);
        kButton7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton7.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton7.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton7.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton7.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton7.setkPressedColor(new java.awt.Color(255, 0, 102));
        kButton7.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        pnlInventario.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, 80));

        kButton8.setText("Mostrar & Buscar");
        kButton8.setBorderPainted(false);
        kButton8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton8.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton8.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton8.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton8.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        pnlInventario.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 160, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marginalia-productive-work.png"))); // NOI18N
        pnlInventario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 250, 230));

        jPanel2.add(pnlInventario, "card4");

        pnlProductos.setBackground(new java.awt.Color(18, 30, 49));
        pnlProductos.setMaximumSize(new java.awt.Dimension(820, 720));
        pnlProductos.setMinimumSize(new java.awt.Dimension(820, 720));
        pnlProductos.setPreferredSize(new java.awt.Dimension(820, 720));
        pnlProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlProductos.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 110));

        jLabel45.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(153, 153, 153));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Gestionar productos");
        pnlProductos.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 500, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sinFD.png"))); // NOI18N
        pnlProductos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 40, 56));
        jLabel11.setText("Burnz Buttly");
        pnlProductos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        jPanel8.setBackground(new java.awt.Color(18, 30, 49));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelHora4.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelHora4.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        jPanel8.add(rSLabelHora4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 290, 70));

        rSLabelFecha4.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelFecha4.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        jPanel8.add(rSLabelFecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, -1));

        pnlProductos.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 380, 210));

        kButton9.setText("Registrar Productos");
        kButton9.setBorderPainted(false);
        kButton9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton9.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton9.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton9.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton9.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton9.setkPressedColor(new java.awt.Color(255, 0, 102));
        kButton9.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });
        pnlProductos.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, 80));

        kButton10.setText("Mostrar & Buscar");
        kButton10.setBorderPainted(false);
        kButton10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton10.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton10.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton10.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton10.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton10.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton10.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });
        pnlProductos.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 160, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pale-order-completed(1).png"))); // NOI18N
        pnlProductos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 260, 230));

        jPanel2.add(pnlProductos, "card5");

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 930, 410));

        jPanel1.setBackground(new java.awt.Color(29, 50, 76));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salida.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 40, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_male_user_30px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, -1));

        kButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_staff_30px.png"))); // NOI18N
        kButton3.setBorderPainted(false);
        kButton3.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton3.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton3.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 60));

        kButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_open_box_30px.png"))); // NOI18N
        kButton4.setBorderPainted(false);
        kButton4.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton4.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton4.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 60));

        kButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_trolley_30px.png"))); // NOI18N
        kButton2.setBorderPainted(false);
        kButton2.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton2.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(22, 32, 45));
        kButton2.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 410));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(54, 38, 87));
        jPanel11.setPreferredSize(new java.awt.Dimension(300, 720));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(lblUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 410));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "¿Estas seguro de modificar tus datos?", "Modificando", JOptionPane.INFORMATION_MESSAGE);
        if (confirm == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
    main.irRegister(this, dt);
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        main.irShowUser(this, dt);
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        pnlUsers.setVisible(true);
        pnlInventario.setVisible(false);
        pnlProductos.setVisible(false);
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        pnlUsers.setVisible(false);
        pnlInventario.setVisible(false);
        pnlProductos.setVisible(true);
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        pnlUsers.setVisible(false);
        pnlInventario.setVisible(true);
        pnlProductos.setVisible(false);
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        main.irInventario1(this, dt);
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        main.irShowInventory(this, dt);
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
       main.irProductos1(this, dt);
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed
        main.irShowProduct(this, dt);
    }//GEN-LAST:event_kButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private keeptoo.KButton kButton10;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton5;
    private keeptoo.KButton kButton6;
    private keeptoo.KButton kButton7;
    private keeptoo.KButton kButton8;
    private keeptoo.KButton kButton9;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlUsers;
    private rojeru_san.RSLabelFecha rSLabelFecha2;
    private rojeru_san.RSLabelFecha rSLabelFecha4;
    private rojeru_san.RSLabelFecha rSLabelFecha5;
    private rojeru_san.RSLabelHora rSLabelHora2;
    private rojeru_san.RSLabelHora rSLabelHora4;
    private rojeru_san.RSLabelHora rSLabelHora5;
    // End of variables declaration//GEN-END:variables
}
