package view;

import controller.Pila;
import controller.inventarioCarrosCr;
import controller.userCreate;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.registro;

/**
 *
 * @author yonier
 */
public class mostrarInventario extends javax.swing.JPanel {

    DefaultTableModel model = new DefaultTableModel();
    registro r;
    TableRowSorter trs; // Clasificar las filas de una tabla

    private main main;
    private userCreate dt;
    private inventarioCarrosCr ic;

    public mostrarInventario(main main, userCreate dt) {
        this.main = main; 
        this.dt = dt;
        initComponents();
        r = new registro();
        mostrar();
    }

    private void mostrar() {
        this.model.addColumn("Placa");
        this.model.addColumn("Modelo");
        this.model.addColumn("Color");
        this.model.addColumn("NoMotor");
        this.model.addColumn("Ciudad");
        this.model.addColumn("Marca");
        this.model.addColumn("Tipo");
        //this.model.addColumn("Imagen");
        tablaInventario.setModel(model);
        //Creo el objeto de tipo inventarioCarrosCr
        Pila<inventarioCarrosCr> datos = r.mostrarinventario();

        if (datos != null) {
            //Creo las filas de la tabla
            Object[] filas = new Object[8];
            try {
                //Recorro el tamaño de la pila
                for (int i = 0; i < datos.size(); i++) {
                    //Asigno el valor de la pila en cada variable a 
                    //cada pocision de la tabla
                    filas[0] = (datos.get(i).getPlaca());
                    filas[1] = (datos.get(i).getModelo());
                    filas[2] = (datos.get(i).getColor());
                    filas[3] = (datos.get(i).getNoMotor());
                    filas[4] = (datos.get(i).getCiudad());
                    filas[5] = (datos.get(i).getMarca());
                    filas[6] = (datos.get(i).getTipoc());
                    //filas[7] = (datos.get(i).getImagen());
                    model.addRow(filas);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al consultar los datos!!");
                e.printStackTrace();
                e.getLocalizedMessage();
            }
        }
    }

    private void borrar() {
        try {
            String dato = txtSearch.getText();

            Pila<inventarioCarrosCr> borrar = r.eliminarInventario(dato);

            if (borrar != null) {
                int i = 0;
                for (; i < borrar.size(); i--) {
                    borrar.remove(i).getPlaca();
                    borrar.remove(i).getModelo();
                    borrar.remove(i).getColor();
                    borrar.remove(i).getNoMotor();
                    borrar.remove(i).getCiudad();
                    borrar.remove(i).getMarca();
                    borrar.remove(i).getTipoc();

                    lblTamanio.setText(String.valueOf(i));

                    System.out.println("DATOS BORRADOS!");
                    System.out.println(borrar.remove(i).getPlaca());
                    System.out.println(borrar.remove(i).getModelo());
                    System.out.println(borrar.remove(i).getColor());
                    System.out.println(borrar.get(i).getNoMotor());
                    System.out.println(borrar.get(i).getCiudad());
                }

            }

        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, "Error inesperado, estamos trabajando en ello!", "Error", JOptionPane.ERROR_MESSAGE);
            //System.out.println("Este error es de la vista " + ex.getMessage() + "  \n" + ex.getLocalizedMessage());
        }
    }

    private void filtro() {
        txtSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearch.getText(), 0));
            }
        });
        trs = new TableRowSorter(model);
        tablaInventario.setRowSorter(trs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_modificar = new keeptoo.KButton();
        btn_eliminar = new keeptoo.KButton();
        txtSearch = new LIB.FSTexFieldMD();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInventario);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 870, 480));

        jPanel2.setBackground(new java.awt.Color(54, 38, 87));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_back_16px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_modificar.setBackground(new java.awt.Color(86, 70, 117));
        btn_modificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 38, 87)));
        btn_modificar.setText("Modificar");
        btn_modificar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_modificar.setkBackGroundColor(new java.awt.Color(51, 51, 255));
        btn_modificar.setkEndColor(new java.awt.Color(51, 153, 255));
        btn_modificar.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        btn_modificar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_modificar.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        btn_modificar.setkSelectedColor(new java.awt.Color(255, 102, 153));
        btn_modificar.setkStartColor(new java.awt.Color(54, 38, 87));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.setkBackGroundColor(new java.awt.Color(51, 51, 255));
        btn_eliminar.setkEndColor(new java.awt.Color(51, 153, 255));
        btn_eliminar.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        btn_eliminar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_eliminar.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        btn_eliminar.setkSelectedColor(new java.awt.Color(255, 102, 153));
        btn_eliminar.setkStartColor(new java.awt.Color(54, 38, 87));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 170, 40));

        txtSearch.setBackground(new java.awt.Color(54, 38, 87));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBordeColorNoFocus(new java.awt.Color(153, 153, 255));
        txtSearch.setMaterialDesing(true);
        txtSearch.setPlaceholder("Buscar y eliminar");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_database_backup_30px_1.png"))); // NOI18N
        jLabel3.setText("  Actualizar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 100, 40));

        jLabel4.setBackground(new java.awt.Color(54, 38, 87));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar por placa");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, -1));

        lblTamanio.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(lblTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 445, 20, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Burnz Buttly");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sinFD.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 100));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        main.irmenu(this, dt);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        main.irModificarInventario(this, dt, ic);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        borrar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        filtro();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        mostrar();
    }//GEN-LAST:event_jLabel3MouseClicked

    void setColor(JPanel panel) {
        panel.setBackground(new Color(86, 70, 117));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(65, 48, 100));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_eliminar;
    private keeptoo.KButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JTable tablaInventario;
    private LIB.FSTexFieldMD txtSearch;
    // End of variables declaration//GEN-END:variables
}
