package view;

import controller.userCreate;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import lib.TextPrompt;
import model.registro;

/**
 *
 * @author Karen Espitia
 */
public class Registrarproducto extends javax.swing.JPanel {

    registro rg = new registro();
    private main main;
    private userCreate dt;

    public Registrarproducto(main main, userCreate dt) {
        this.main = main;
        this.dt = dt;
        initComponents();
        placeholders();
        btn_ver.setVisible(false);
        txtimagen.setVisible(false);
        kButton3.setVisible(false);
        btnNuevo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRound1 = new LIB.JPanelRound();
        imagen = new javax.swing.JLabel();
        tipoprod = new javax.swing.JComboBox<>();
        txtreferencia = new javax.swing.JTextField();
        txtnombrepro = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtcant = new javax.swing.JTextField();
        txtimagen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areAplicacion = new javax.swing.JTextArea();
        txtprecio = new javax.swing.JTextField();
        indice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_ver = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        kButton1 = new keeptoo.KButton();
        btnNuevo = new keeptoo.KButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 40, 56));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound1.setBackground(new java.awt.Color(27, 40, 56));
        jPanelRound1.setColorPrimario(new java.awt.Color(27, 40, 56));
        jPanelRound1.setColorSecundario(new java.awt.Color(27, 40, 56));
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setForeground(new java.awt.Color(0, 0, 0));
        jPanelRound1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 180, 160));

        tipoprod.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tipoprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cojineria", "Limpieza", "Accesorio", "Llanta", "Sonido", " ", " " }));
        tipoprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoprodActionPerformed(evt);
            }
        });
        jPanelRound1.add(tipoprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 100, -1));
        jPanelRound1.add(txtreferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, -1));
        jPanelRound1.add(txtnombrepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, -1));
        jPanelRound1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 130, -1));

        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });
        jPanelRound1.add(txtcant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 80, 30));

        txtimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimagenActionPerformed(evt);
            }
        });
        jPanelRound1.add(txtimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 170, -1));

        areAplicacion.setColumns(20);
        areAplicacion.setRows(5);
        jScrollPane1.setViewportView(areAplicacion);

        jPanelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, -1));
        jPanelRound1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 170, -1));

        indice.setBackground(new java.awt.Color(27, 40, 56));
        indice.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        indice.setText("3");
        indice.setEnabled(false);
        indice.setOpaque(true);
        jPanelRound1.add(indice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registrar Producto");
        jPanelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 510, -1));

        btn_ver.setText("Ver");
        btn_ver.setBorderPainted(false);
        btn_ver.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_ver.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        btn_ver.setkEndColor(new java.awt.Color(102, 102, 255));
        btn_ver.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        btn_ver.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_ver.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        btn_ver.setkSelectedColor(new java.awt.Color(255, 102, 153));
        btn_ver.setkStartColor(new java.awt.Color(22, 32, 45));
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });
        jPanelRound1.add(btn_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 40, 20));

        kButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_upload_to_cloud_16px_1.png"))); // NOI18N
        kButton3.setText("Seleccionar");
        kButton3.setBorderPainted(false);
        kButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton3.setIconTextGap(8);
        kButton3.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton3.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        kButton3.setkSelectedColor(new java.awt.Color(255, 102, 153));
        kButton3.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanelRound1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 130, -1));

        kButton1.setText("Aceptar");
        kButton1.setToolTipText("");
        kButton1.setBorderPainted(false);
        kButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        kButton1.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        kButton1.setkSelectedColor(new java.awt.Color(255, 102, 153));
        kButton1.setkStartColor(new java.awt.Color(22, 32, 45));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanelRound1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 130, 40));

        btnNuevo.setText("Nuevo");
        btnNuevo.setBorderPainted(false);
        btnNuevo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnNuevo.setkBackGroundColor(new java.awt.Color(22, 32, 45));
        btnNuevo.setkEndColor(new java.awt.Color(102, 102, 255));
        btnNuevo.setkHoverEndColor(new java.awt.Color(255, 0, 102));
        btnNuevo.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNuevo.setkHoverStartColor(new java.awt.Color(54, 38, 87));
        btnNuevo.setkSelectedColor(new java.awt.Color(255, 102, 153));
        btnNuevo.setkStartColor(new java.awt.Color(22, 32, 45));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanelRound1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 100, 40));

        add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 460, 560));

        jPanel1.setBackground(new java.awt.Color(27, 40, 56));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 10, 570));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_back_16px_1.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fdReProduc.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void txtimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimagenActionPerformed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        main.irmenu(this, dt);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void tipoprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoprodActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        main.irmostrarInventario(this, dt);
    }//GEN-LAST:event_btn_verActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        //CLase JFileChooser
        //Filtro para buscar imagen
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG; *.JPEG)", "jpg", "jpeg");

        JFileChooser img = new JFileChooser();
        img.addChoosableFileFilter(filtro);
        img.setDialogTitle("Abrir Archivo");
        //Declaro para que se abra la ventana del buscador
        int ventana = img.showOpenDialog(null);
        //Condicional para ver si se seleccionó un archivo
        if (ventana == JFileChooser.APPROVE_OPTION) {
            File fl = img.getSelectedFile();
            //Mostrar la ruta del archivo
            txtimagen.setText(String.valueOf(fl));
            //Imprimir imagen  seleccionada en el label
            Image imag = getToolkit().getImage(txtimagen.getText());
            imag = imag.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            imagen.setIcon(new ImageIcon(imag));

        }
    }//GEN-LAST:event_kButton3ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        agregarinv();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void agregarinv() {

        //FileInputStream archivarfoto = null;
        String referencia = txtreferencia.getText();
        String nombre = txtnombrepro.getText();
        String marca = txtmarca.getText();
        String tipoca = tipoprod.getSelectedItem().toString();
        String aplicacion = areAplicacion.getText();
        int cantidad = Integer.parseInt(txtcant.getText());
        double precio = Double.parseDouble(txtprecio.getText());
        String in = indice.getText();
//        try {
//            archivarfoto = new FileInputStream(txtimagen.getText());
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(Registrarproducto.class.getName()).log(Level.SEVERE, null, ex);
//        }
        if (txtreferencia.getText().equals("") || nombre.equals("") || marca.equals("") || tipoprod.equals("") || aplicacion.equals("") || txtcant.getText().equals("") || txtprecio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor llena todos los campos!");
        }
        //boolean registrar = rg.registrarproducto(referencia, nombre, marca, tipoca, aplicacion, cantidad, precio, archivarfoto, in);
        boolean registrar = rg.registrarproducto(referencia, nombre, marca, tipoca, aplicacion, cantidad, precio);
        if (registrar != false) {
            JOptionPane.showMessageDialog(null, "¡Registro exito!");
            limpiar();
            btnNuevo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "¡Error al registrar el producto, estamos trabajando el ello...!");
            //btn_ver.setVisible(false);
        }

    }

    public final void placeholders() {
        TextPrompt nombre = new TextPrompt(" Referencia", txtreferencia);
        TextPrompt direccion = new TextPrompt(" Nombre", txtnombrepro);
        TextPrompt telefono = new TextPrompt(" Marca", txtmarca);
        TextPrompt email = new TextPrompt(" Aplicacion, escriba para que \n sirve este producto", areAplicacion);
        TextPrompt cedula = new TextPrompt(" Cantidad", txtcant);
        TextPrompt ciudad = new TextPrompt(" Precio", txtprecio);
        TextPrompt img = new TextPrompt(" Selecciona una imagen", txtimagen);
    }

    public void limpiar() {
        txtreferencia.setText("");
        txtnombrepro.setText("");
        txtmarca.setText("");
        txtcant.setText("");
        txtmarca.setText("");
        txtimagen.setText("");
        txtprecio.setText("");
        areAplicacion.setText("");

        txtreferencia.setEditable(false);
        txtnombrepro.setEditable(false);
        txtmarca.setEditable(false);
        txtcant.setEditable(false);
        txtmarca.setEditable(false);
        txtimagen.setEditable(false);
        txtprecio.setEditable(false);
        areAplicacion.setEditable(false);

    }

    private void nuevo() {
        txtreferencia.setEditable(true);
        txtnombrepro.setEditable(true);
        txtmarca.setEditable(true);
        txtcant.setEditable(true);
        txtmarca.setEditable(true);
        txtimagen.setEditable(true);
        txtprecio.setEditable(true);
        areAplicacion.setEditable(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areAplicacion;
    private keeptoo.KButton btnNuevo;
    private keeptoo.KButton btn_ver;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel indice;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton3;
    private javax.swing.JComboBox<String> tipoprod;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtimagen;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtnombrepro;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtreferencia;
    // End of variables declaration//GEN-END:variables
}
