package view;

import controller.userCreate;
import java.util.TimerTask;

/**
 *
 * @author samir
 */
public class SplahsCreen2 extends javax.swing.JPanel {

    private main main;
    private userCreate dt;

    public SplahsCreen2(main main, userCreate dt) {
        this.main = main;
        this.dt = dt;
        initComponents();
        animacion();
    }

    public final void animacion() {
        new java.util.Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                //mensajes.setText("    ¡Iniciando...!");
                principallogin();
            }
        }, 6000);
    }

    private void principallogin() {
        main.irmenuUsers(this, dt);
        //JOptionPane.showMessageDialog(null, "Bienvenido!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cargar = new javax.swing.JLabel();
        labelMensaje = new javax.swing.JLabel();
        mensajes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(24, 27, 62));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 115, 158));
        jLabel2.setText("Burnz Buttly");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        cargar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ed (1).gif"))); // NOI18N
        cargar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        cargar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cargarFocusGained(evt);
            }
        });
        add(cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 630, 120));

        labelMensaje.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        labelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        labelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensaje.setText("Para todo lo demas, existe Burnz Buttly");
        add(labelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 630, 20));

        mensajes.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        mensajes.setForeground(new java.awt.Color(255, 255, 255));
        mensajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajes.setText("Hay cosas que el dinero no puede comprar");
        add(mensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/splash.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void cargarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cargarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel mensajes;
    // End of variables declaration//GEN-END:variables
}
